### ISSUE TITLE
Comentario

### ISSUE THREAD

**Issue by lunabytes** [sk00617/java-lessons#16]
https://github.com/sk00617/java-lessons/blob/1a05d3c15051c3bf61baa2bfa4dacaa8ae12dd58/QuickSort/src/quicksort/StringSort.java#L10

Esta bien que utilices la clase con todo el paquete ya que solo es una clase sencilla, en un proyecto más grande mejor importar la clase y así tener visualización de todos los objetos de los cuales tenemos dependencias.

**Comment by sk00617** [comment]
Okay. Importé la clase y modifiqué esa línea.
