### ISSUE TITLE
Agregar Validación

### ISSUE THREAD

**Issue by lunabytes** [sk00617/java-lessons#23]
https://github.com/sk00617/java-lessons/blob/e7eb7bcad878b1445c0c3cf5510db88b0e13a61d/Palindrome/src/palindrome/Palindrome.java#L5

Con esta expresión regular filtras vocales con tildes como á, é, etc. y eso no seria lo correcto, podrias corregirlo

Gracias

**Comment by sk00617** [comment]
Se reemplazaron las vocales con tilde por vocales sin tilde antes de la llamada a replaceAll.
